### PR TITLE
Revert "Add auto-detect for current semester; ics enhancement"

### PR DESCRIPTION
**Pull request by BishopOfTurkey**
Reverts catmanjan/anutimetable#380

Timetable broke after merge...
image

### CODE REVIEW

**Comment by Lutra-Fs** [comment]
I will see what's going on

**Comment by Lutra-Fs** [comment]
It is good in my fork

**Comment by Lutra-Fs** [comment]
Hi @BishopOfTurkey, it looks like it to be a merge problem. I will re-create the PR, make sure to use my branch's file to overwrite the original file.

**Comment by BishopOfTurkey** [comment]
My bad, was doing it in the browser and didn't see what I was changing

**Comment by Lutra-Fs** [comment]
Looks like you will need to revert your reversion first... Sry I cannot push the existing commits again.

**Pull request merged**
