### PR TITLE
Full screen dismissable dialog advertising the new timetable.cssa.club site

### PR DESCRIPTION
**Pull request by OliverBalfour**
Here's what it looks like when I inject the HTML and CSS I've added into anutimetable.com:

image

I assume inserting the code into both HTML files will do the trick

I've also updated the README to direct people to the new repo

@BishopOfTurkey we're still putting in the finishing touches on timetable.cssa.club so I'd appreciate it if you could review/approve these changes now, but hold off on merging them until Tom Plant and I agree it's ready

### CODE REVIEW

**Comment by pl4nty** [comment]
Thanks Oliver, agreed. Do we want migrate some feature requests too? #77, #83, #92/#148, and #103 might be worth reviewing.

**Comment by OliverBalfour** [comment]
Yeah, after the release we could maybe do:
* 77: SEO (or at least indexing) seems useful! We can leverage existing anutimetable.com SEO with this fix for now IMO
* 103: Instead maybe a hide button on events that persists into query string and ICS export, so you can exclude prerecorded lectures from your linked calendar?
* 83: very low priority but could be useful, would need query string persistence + ICS integration

I'll open tickets in the new repo

**Comment by pl4nty** [comment]
Brilliant, we had pretty much the same ideas lol. Prerecorded is a great point too. Config might not have to persist in the qs (maybe local or session storage instead), just in the ics export, but maybe it's safer to share the same state/API across both.

**Comment by BishopOfTurkey** [comment]
looks good

@catmanjan looks like the ol' anutimetable is end of life. Hopefully if you are paying for the domain you could get in contact with the cssa and ask them if they want to take ownership of it at https://cssa.club/discord

**Comment by OliverBalfour** [comment]
@BishopOfTurkey we're ready - could you merge this when you get the chance? Thanks

**Pull request merged**
